#!/bin/bash

function require {
	cmd=$1
	error_message=$2

	result=$($cmd &> /dev/null)
	[ $? -eq 0 ] || { echo "$error_message"; exit 1; }
}

function require_not_empty {
	var=$1
	error_message=$2
	[ "$var" != "" ] || { echo "$error_message"; exit 1; }
}

function require_file_not_exists {
	var=$1
	error_message=$2
	[ -f "$PROJ" -o -d "$PROJ" ] && { echo "$error_message"; exit 1; }
}

require "perl -v"            "perl is not installed"
require "hub --version"      "hub is not installed, visit https://github.com/github/hub"


PROJ=$1
require_not_empty "$PROJ"            "project name is mandatory"
require_file_not_exists "$PROJ"      "file or directory \"$PROJ\" already exists"

MY_GITHUB_USERNAME=$( perl -ne 'print "$1" if /user: (.*?)\n/' ~/.config/hub )

SEED="jorgeviana/simple-java-seed"

hub clone $SEED $PROJ
cd $PROJ

rm -rf .git/
git init

git add .
git commit -m "initial commit"



HAS_COLLABORATORS=$2
[ "$HAS_COLLABORATORS" != "" ] || exit

hub create
git push origin master


shift 1
for COLLABORATOR in "$@"
do 
  hub api -X PUT repos/$MY_GITHUB_USERNAME/$PROJ/collaborators/$COLLABORATOR
done

echo "https://github.com/$MY_GITHUB_USERNAME/$PROJ/invitations"
echo