#!/bin/bash

hub --version &> /dev/null
[ $? -eq 0 ] || { echo "hub is not installed, visit https://github.com/github/hub"; exit 1; }

# proj myproj -s jorgeviana/simple-java-seed -c COL1 -c COL2 -g jorgeviana

#PROJ="${1:-}"
PROJ=$1
[ "$PROJ" == "" ] && { echo "project name is mandatory"; exit 1; }
[ -f "$PROJ" -o -d "$PROJ" ] && { echo "file or directory \"$PROJ\" already exists"; exit 1; }

MY_GITHUB_USERNAME=$( perl -ne 'print "$1" if /user: (.*?)\n/' ~/.config/hub )

SEED="jorgeviana/simple-java-seed"

hub clone $SEED $PROJ
cd $PROJ

rm -rf .git/
git init

git add .
git commit -m "initial commit"



HAS_COLLABORATORS=$2
[ "$HAS_COLLABORATORS" != "" ] || exit

hub create
git push origin master


shift 1
for COLLABORATOR in "$@"
do 
  hub api -X PUT repos/$MY_GITHUB_USERNAME/$PROJ/collaborators/$COLLABORATOR
done

echo "https://github.com/$MY_GITHUB_USERNAME/$PROJ/invitations"
echo